apiVersion: v1
kind: PersistentVolume
metadat:
    name: pv-vol1
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 1Gi
    awsElasticBlockStore:
        volumeID: <volid>
        fsType: ext4
        